// Code generated by gobusgen; DO NOT EDIT.
package events

import (
	"context"
	"sync"
)

// Event represents a typed event name.
type Event string

const (
	EventRecipeMutation      Event = "recipe.mutation"
	EventShoppingListCleanup Event = "shopping_list.cleanup"
	EventUserRegistration    Event = "user.registration"
)

// EventBus provides type-safe publish/subscribe for in-process events.
type EventBus struct {
	mu          sync.RWMutex
	subscribers map[Event][]any
	ch          chan envelope
}

type envelope struct {
	event   Event
	payload any
}

// New creates an EventBus with the given channel buffer size.
func New(size int) *EventBus {
	return &EventBus{
		subscribers: newSubscribersMap(),
		ch:          make(chan envelope, size),
	}
}

func newSubscribersMap() map[Event][]any {
	return map[Event][]any{
		EventRecipeMutation:      {},
		EventShoppingListCleanup: {},
		EventUserRegistration:    {},
	}
}

// Start begins processing events. It blocks until ctx is cancelled.
func (bus *EventBus) Start(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case env := <-bus.ch:
			bus.mu.RLock()
			subs := make([]any, len(bus.subscribers[env.event]))
			copy(subs, bus.subscribers[env.event])
			bus.mu.RUnlock()

			for _, sub := range subs {
				if fn, ok := sub.(func(any)); ok {
					fn(env.payload)
				}
			}
		}
	}
}

// PublishRecipeMutation publishes a recipe.mutation event.
func (bus *EventBus) PublishRecipeMutation(payload MutationEvent) {
	bus.ch <- envelope{event: EventRecipeMutation, payload: payload}
}

// SubscribeRecipeMutation registers a handler for recipe.mutation events.
func (bus *EventBus) SubscribeRecipeMutation(fn func(MutationEvent)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventRecipeMutation] = append(bus.subscribers[EventRecipeMutation], func(v any) {
		fn(v.(MutationEvent))
	})
}

// PublishShoppingListCleanup publishes a shopping_list.cleanup event.
func (bus *EventBus) PublishShoppingListCleanup(payload ShoppingListCleanup) {
	bus.ch <- envelope{event: EventShoppingListCleanup, payload: payload}
}

// SubscribeShoppingListCleanup registers a handler for shopping_list.cleanup events.
func (bus *EventBus) SubscribeShoppingListCleanup(fn func(ShoppingListCleanup)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventShoppingListCleanup] = append(bus.subscribers[EventShoppingListCleanup], func(v any) {
		fn(v.(ShoppingListCleanup))
	})
}

// PublishUserRegistration publishes a user.registration event.
func (bus *EventBus) PublishUserRegistration(payload UserRegistrationEvent) {
	bus.ch <- envelope{event: EventUserRegistration, payload: payload}
}

// SubscribeUserRegistration registers a handler for user.registration events.
func (bus *EventBus) SubscribeUserRegistration(fn func(UserRegistrationEvent)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventUserRegistration] = append(bus.subscribers[EventUserRegistration], func(v any) {
		fn(v.(UserRegistrationEvent))
	})
}

// Reference the source variable to suppress unused-variable lint.
var _ = Events
