package generator

import (
	"text/template"

	"github.com/hay-kot/gobusgen/internal/model"
)

var tmpl = template.Must(template.New("eventbus").Funcs(template.FuncMap{
	"pascalCase": model.PascalCase,
}).Parse(eventBusTemplate))

const eventBusTemplate = `// Code generated by gobusgen; DO NOT EDIT.
package {{ .PackageName }}

import (
	"context"
	"sync"
)

// Event represents a typed event name.
type Event string

const (
{{- range .Events }}
	{{ $pc := pascalCase .Name -}}
	Event{{ $pc }} Event = "{{ .Name }}"
{{- end }}
)

// EventBus provides type-safe publish/subscribe for in-process events.
type EventBus struct {
	mu          sync.RWMutex
	subscribers map[Event][]any
	ch          chan envelope
}

type envelope struct {
	event   Event
	payload any
}

// New creates an EventBus with the given channel buffer size.
func New(size int) *EventBus {
	if size < 1 {
		size = 1
	}

	return &EventBus{
		subscribers: newSubscribersMap(),
		ch:          make(chan envelope, size),
	}
}

func newSubscribersMap() map[Event][]any {
	return map[Event][]any{
{{- range .Events }}
	{{ $pc := pascalCase .Name -}}
		Event{{ $pc }}: {},
{{- end }}
	}
}

// Start begins processing events. It blocks until ctx is cancelled.
func (bus *EventBus) Start(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case env := <-bus.ch:
			bus.mu.RLock()
			subs := make([]any, len(bus.subscribers[env.event]))
			copy(subs, bus.subscribers[env.event])
			bus.mu.RUnlock()

			for _, sub := range subs {
				if fn, ok := sub.(func(any)); ok {
					fn(env.payload)
				}
			}
		}
	}
}

{{ range .Events }}
{{ $pc := pascalCase .Name -}}
// Publish{{ $pc }} publishes a {{ .Name }} event.
func (bus *EventBus) Publish{{ $pc }}(payload {{ .PayloadType }}) {
	bus.ch <- envelope{event: Event{{ $pc }}, payload: payload}
}

// Subscribe{{ $pc }} registers a handler for {{ .Name }} events.
func (bus *EventBus) Subscribe{{ $pc }}(fn func({{ .PayloadType }})) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[Event{{ $pc }}] = append(bus.subscribers[Event{{ $pc }}], func(v any) {
		payload, ok := v.({{ .PayloadType }})
		if !ok {
			return
		}
		fn(payload)
	})
}
{{ end }}
// Reference the source variable to suppress unused-variable lint.
var _ = {{ .VarName }}
`
